name: test pipeline
on: push
concurrency: test-pipeline
jobs:
  deploy2dev:
    uses: ./.github/workflows/deploy.yaml
    with:
      DEPLOY2ENV: dev
  deploy2stage:
    needs: deploy2dev
    uses: ./.github/workflows/deploy.yaml
    with:
      DEPLOY2ENV: stage
  deploy2prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy2stage
    uses: ./.github/workflows/deploy.yaml
    with:
      DEPLOY2ENV: prod
