name: PR Comment
on: pull_request

jobs:
  pr_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PR Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            const body = 'Hello, this is a comment from a GitHub Action!';
            github.issues.createComment({ owner, repo, issue_number: number, body });
